import { PrismaClient, EventType, TeamRole } from '@prisma/client'; import bcrypt from 'bcryptjs';
const p=new PrismaClient();
async function main(){
 const hash=await bcrypt.hash('admin123',12); await p.user.upsert({where:{email:'admin@classicfamilyphotography.com'},update:{},create:{email:'admin@classicfamilyphotography.com',name:'Studio Admin',passwordHash:hash}});
 await p.studioSettings.upsert({where:{id:'default'},update:{},create:{id:'default',phone:'+91 99999 99999',whatsapp:'919999999999',email:'hello@classicfamilyphotography.com',address:'Bhopal, Madhya Pradesh, India',workingHours:'Monday–Saturday, 9:00 AM–9:00 PM'}});
 if(await p.package.count()===0){await p.package.createMany({data:[{name:'Classic Wedding Package',price:60000,description:'A timeless wedding coverage package.',features:['Candid Photography','Traditional Photography','Wedding Cinematography','Highlight Film']},{name:'Premium Wedding Package',price:100000,description:'Full-service coverage for the complete celebration.',features:['Candid Photography','Traditional Photography','Cinematography','Pre-Wedding','Drone Coverage','Highlight Film']} ]});}
 if(await p.teamMember.count()===0){await p.teamMember.createMany({data:[{name:'Amit',role:TeamRole.PHOTOGRAPHER},{name:'Rohit',role:TeamRole.VIDEOGRAPHER},{name:'Sameer',role:TeamRole.CINEMATOGRAPHER}]});}
 if(await p.galleryImage.count()===0){const imgs=['https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1400&q=85','https://images.unsplash.com/photo-1606800052052-a08af7148866?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1537633552985-df8429e8048b?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1000&q=85']; const cats=['Weddings','Weddings','Pre-Wedding','Cinematography','Modelling','Events']; for(let i=0;i<imgs.length;i++) await p.galleryImage.create({data:{title:['Wedding Ceremony','Bride & Groom Portrait','Pre-Wedding Couple Shoot','Cinematic Wedding','Model Portfolio','Reception'][i],category:cats[i],url:imgs[i],featured:i<4}})}
}
main().finally(()=>p.$disconnect());
